# Handling Missing Values (arreglando valores perdidos)

Ya tocamos el tema de que como manejar los valores categoricos para usarlos en una regresion para hacer una prediccion. Hemos visto que entre mas datos manejemos, es decir tengamos, nuestra prediccion puede ser mas certera.

En algunas ocaciones, existiran valores que no tengan un valor real como tal, su ausencia tambien puede ser interpretada intuitivamente. Los valores perdidos (missing values) tienden a poder ser remplazados o no ser utilizados cuando se trata de analizar los datos. Ya vismo que podemos remplazarlos, aunque tambien existen otros metodos para no quedarnos sin esos datos.

## Entontremos esos valores perdidos

Cuando se trate de dejar valores perdidos, veremos que pandas no permite que las casillas donde el valor deberia de ir no hay nada. Al no haber nada, pandas lo remplazara con NULL el lugar donde deberia de haber algo y cuando tratemos de ver el numero total de valores que hay en una columna entonces todos esos valores Null no formaran parte del resultado.

In [2]:
import pandas as pd
import numpy as np

nfl_data = pd.read_csv("data/NFL Play by Play 2009-2017 (v4).csv")
np.random.seed(0)

C:\Users\CDWLu\AppData\Local\Temp\ipykernel_19872\83059129.py:4: DtypeWarning: Columns (25,51) have mixed types. Specify dtype option on import or set low_memory=False.
  nfl_data = pd.read_csv("data/NFL Play by Play 2009-2017 (v4).csv")

La primera recomendacion cuando se trata de analizar los datos, es echarle un vistazo a lo que tenemos.

In [3]:
nfl_data.head()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

Vemos que hay datos que los marca como NaN (Not a Number). Aquellos datos NaN, a veces NULL, son aquellos que debemos manejar con cuidado. Eso lo hacemos ya que si tenemos un gran porcentaje de datos perdidos, por ejemplo un poco mas del 20%, estariamos perdiendo la misma cantidad de informacion. Ademas, un dato que no existe puede tener muchas expliaciones dependiendo de la informacion que se este pidiendo, ya que en algunas ocaciones es posible que el registro no se haga de forma deliberada y quien halla pedido ese datos no halla hecho algo al respecto cuando se tratara de un caso asi, como dar un valor por defecto en caso de que se elija no dar uno.

## Cuantos valores perdidos tenemos

Ahora, calculemos cuanta informacion no tenemos.

In [4]:
missing_values_count = nfl_data.isnull().sum()

missing_values_count[0:10]

Date                0
GameID              0
Drive               0
qtr                 0
down            61154
time              224
TimeUnder           0
TimeSecs          224
PlayTimeDiff      444
SideofField       528
dtype: int64

Vemos que el valor con mas datos perdidos es `down`.

In [7]:
total_cells = np.prod(nfl_data.shape)
total_missing = missing_values_count.sum()

percent_missing = (total_missing/total_cells) * 100
print(percent_missing)

27.66722370547874

Vemos que el total de informacion queno hay en el dataset es de casi el 28%, en perspectiva, esa es mucha informacion. Si decidieramos solo no tomar encuenta esos datos que no hay entonces no habria alguna buena prediccion realmente.

## Eliminando la missing data

Supongamos que decidimos que es buena idea eliminar la informacion perdida, entonces, hagamoslo

In [8]:
nfl_data.dropna()

Empty DataFrame
Columns: [Date, GameID, Drive, qtr, down, time, TimeUnder, TimeSecs, PlayTimeDiff, SideofField, yrdln, yrdline100, ydstogo, ydsnet, GoalToGo, FirstDown, posteam, DefensiveTeam, desc, PlayAttempted, Yards.Gained, sp, Touchdown, ExPointResult, TwoPointConv, DefTwoPoint, Safety, Onsidekick, PuntResult, PlayType, Passer, Passer_ID, PassAttempt, PassOutcome, PassLength, AirYards, YardsAfterCatch, QBHit, PassLocation, InterceptionThrown, Interceptor, Rusher, Rusher_ID, RushAttempt, RunLocation, RunGap, Receiver, Receiver_ID, Reception, ReturnResult, Returner, BlockingPlayer, Tackler1, Tackler2, FieldGoalResult, FieldGoalDistance, Fumble, RecFumbTeam, RecFumbPlayer, Sack, Challenge.Replay, ChalReplayResult, Accepted.Penalty, PenalizedTeam, PenaltyType, PenalizedPlayer, Penalty.Yards, PosTeamScore, DefTeamScore, ScoreDiff, AbsScoreDiff, HomeTeam, AwayTeam, Timeout_Indicator, Timeout_Team, posteam_timeouts_pre, HomeTimeouts_Remaining_Pre, AwayTimeouts_Remaining_Pre, HomeTimeouts_Remaining_Post, AwayTimeouts_Remaining_Post, No_Score_Prob, Opp_Field_Goal_Prob, Opp_Safety_Prob, Opp_Touchdown_Prob, Field_Goal_Prob, Safety_Prob, Touchdown_Prob, ExPoint_Prob, TwoPoint_Prob, ExpPts, EPA, airEPA, yacEPA, Home_WP_pre, Away_WP_pre, Home_WP_post, Away_WP_post, Win_Prob, WPA, airWPA, ...]
Index: []

[0 rows x 102 columns]

Y hemos visto que yan o hay nada. Afortunadamente no hemos eliminado la informacion realmente, solo hemos eliminado la informacion de esa instancia de memoria. La informacion aun existe, pero hemos visto que eliminarla asi solo por que si entonces nos quita toda la informacion, ahora hagamoslo bien.

In [9]:
columns_with_na_dropped = nfl_data.dropna(axis = 1)
columns_with_na_dropped.head()

,Date,GameID,Drive,qtr,TimeUnder,ydstogo,ydsnet,PlayAttempted,Yards.Gained,sp,...,AwayTeam,Timeout_Indicator,posteam_timeouts_pre,HomeTimeouts_Remaining_Pre,AwayTimeouts_Remaining_Pre,HomeTimeouts_Remaining_Post,AwayTimeouts_Remaining_Post,ExPoint_Prob,TwoPoint_Prob,Season
0,2009-09-10,2009091000,1,1,15,0,0,1,39,0,...,TEN,0,3,3,3,3,3,0.0,0.0,2009
1,2009-09-10,2009091000,1,1,15,10,5,1,5,0,...,TEN,0,3,3,3,3,3,0.0,0.0,2009
2,2009-09-10,2009091000,1,1,15,5,2,1,-3,0,...,TEN,0,3,3,3,3,3,0.0,0.0,2009
3,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,TEN,0,3,3,3,3,3,0.0,0.0,2009
4,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,TEN,0,3,3,3,3,3,0.0,0.0,2009

In [10]:
print("Columnas en la informacion original: %d \n" % nfl_data.shape[1])
print("Columns with na's dropped: %d" %columns_with_na_dropped.shape[1])

Columnas en la informacion original: 102

Columns with na's dropped: 37

La informacion que quedo es apenas una cuarta parte de la informacion original. Lo que paso con la funcion `.drop` fue que, por defecto, este elimina las filas que contienen valores perdidos, cuyo atributo es `axis = 0`. Con el atributo `axis` cambiado a 1 de la funcion, entonces lo que estmos tomando en cuenta son las columnas, por lo que esta ahora elimina columnas y no renglones, es preferible de esta forma ya que casi todos los registros contienen valores perdidos.

## Rellenando los valores perdidos

Otra opcion facil de manejar es el de darle un valor a aquellos valores que hay. Esto depende de cada conjunto de datos.

In [13]:
subset_nfl_data = nfl_data.loc[:, "EPA": "Season"].head()
subset_nfl_data

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,NaN,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,NaN,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,NaN,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

In [14]:
subset_nfl_data.fillna(0)

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,0.000000,0.000000,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,0.000000,0.000000,2009
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,0.000000,0.000000,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.000000,0.000000,2009
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,0.000000,0.000000,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0.000000,0.000000,2009

La funcion `fillna` contiene atributos utiles, para complementar mejor su uso.

In [16]:
subset_nfl_data.fillna(method = 'bfill', axis = 0).fillna(0)

C:\Users\CDWLu\AppData\Local\Temp\ipykernel_19872\4232683824.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  subset_nfl_data.fillna(method = 'bfill', axis = 0).fillna(0)

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,-1.068169,1.146076,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,-0.032244,0.036899,2009
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,3.318841,-5.031425,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.106663,-0.156239,2009
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,0.000000,0.000000,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0.000000,0.000000,2009